[package]
authors = ["Ross MacArthur <ross@macarthur.io>"]
description = "A fast, configurable, shell plugin manager."
edition = "2018"
name = "sheldon"
version = "0.1.0"

[dependencies]
ansi_term = "0.11"
clap = "2"
indexmap = { version = "1", features = ["serde-1"] }
log = "0.4"
serde = "1"
serde_derive = "1"
toml = "0.4"

[dev-dependencies]
tempfile = "3"
