[package]
name = "sheldon"
version = "0.4.8"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
build = "build.rs"

# Metadata (https://doc.rust-lang.org/cargo/reference/manifest.html)
description = "A fast, configurable, shell plugin manager."
homepage = "https://github.com/rossmacarthur/sheldon"
repository = "https://github.com/rossmacarthur/sheldon"
readme = "README.md"
keywords = ["shell", "plugin", "manager", "zsh", "bash"]
categories = ["command-line-utilities"]
license = "MIT OR Apache-2.0"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
ansi_term = "0.11.0"
anyhow = "1.0.28"
casual = "0.1.1"
dirs = "2.0.2"
fs2 = "0.4.3"
git2 = "0.13.1"
glob = "0.3.0"
handlebars = "3.0.1"
indexmap = { version = "1.3.2", features = ["serde-1"] }
itertools = "0.9.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
regex = "1.3.6"
reqwest = { version = "0.10.4", features = ["blocking"] }
scoped_threadpool = "0.1.9"
serde = { version = "1.0.106", features = ["derive"] }
structopt = "0.3.13"
toml = "0.5.6"
toml_edit = "0.1.5"
url = { version = "2.1.1", features = ["serde"] }
walkdir = "2.3.1"
which = { version = "3.1.1", default-features = false }

[dev-dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
tempfile = "3.1.0"
