[package]
name = "sheldon"
version = "0.6.5"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
description = "Fast, configurable, shell plugin manager."
documentation = "https://sheldon.cli.rs"
readme = "README.md"
repository = "https://github.com/rossmacarthur/sheldon"
license = "MIT OR Apache-2.0"
keywords = ["shell", "plugin", "manager", "zsh", "bash"]
categories = ["command-line-utilities"]
build = "build.rs"
include = ["src/**/*", "LICENSE-*", "README.md", "build.rs"]

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.44"
atty = "0.2.14"
casual = "0.2.0"
clap = { version = "3.0.13", features = ["cargo", "env", "derive"] }
curl = "0.4.39"
fs2 = "0.4.3"
git2 = { version = "0.13.23", features = ["vendored-libgit2"] }
globwalk = "0.8.1"
handlebars = "4.1.3"
home = "0.5.3"
indexmap = { version = "1.7.0", features = ["rayon", "serde"] }
itertools = "0.10.1"
maplit = "1.0.2"
once_cell = "1.8.0"
rayon = "1.5.1"
regex-macro = "0.1.1"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"
toml = { version = "0.5.8", features = ["preserve_order"] }
toml_edit = "0.6.0"
url = { version = "2.2.2", features = ["serde"] }
walkdir = "2.3.2"
which = { version = "4.2.2", default-features = false }

[build-dependencies]
anyhow = "1.0.44"

[dev-dependencies]
goldie = "0.1.0"
pest = "2.1.3"
pest_derive = "2.1.0"
pretty_assertions = "1.0.0"
serde_json = "1.0.68"
tempfile = "3.2.0"

[workspace]
members = ["tools/generate-readme"]
