[package]
authors = ["Ross MacArthur <ross@macarthur.io>"]
description = "A fast, configurable, shell plugin manager."
edition = "2018"
homepage = "https://github.com/rossmacarthur/sheldon"
keywords = ["shell", "plugin", "manager", "zsh", "bash"]
license = "Apache-2.0/MIT"
name = "sheldon"
readme = "README.md"
repository = "https://github.com/rossmacarthur/sheldon"
version = "0.1.0"

[dependencies]
ansi_term = "0.11"
clap = "2"
dirs = "1"
git2 = "0.8"
glob = "0.2"
handlebars = "1"
indexmap = { version = "1", features = ["serde-1"] }
maplit = "1"
log = "0.4"
serde = "1"
serde_derive = "1"
toml = "0.4"
url = "1"

[dev-dependencies]
tempfile = "3"
