[target.aarch64-unknown-linux-gnu]
image = "rossmacarthur/sheldon-cross:aarch64-unknown-linux-gnu-0.2.1"

[target.aarch64-unknown-linux-musl]
image = "rossmacarthur/sheldon-cross:aarch64-unknown-linux-musl-0.2.1"

[target.armv7-unknown-linux-gnueabihf]
image = "rossmacarthur/sheldon-cross:armv7-unknown-linux-gnueabihf-0.2.1"

[target.armv7-unknown-linux-musleabihf]
image = "rossmacarthur/sheldon-cross:armv7-unknown-linux-musleabihf-0.2.1"

[target.x86_64-unknown-linux-gnu]
image = "rossmacarthur/sheldon-cross:x86_64-unknown-linux-gnu-0.2.1"

[target.x86_64-unknown-linux-musl]
image = "rossmacarthur/sheldon-cross:x86_64-unknown-linux-musl-0.2.1"
