# Example ~/.sheldon/plugins.toml file
#
# This file mostly shows the default values for config settings. Most of the
# time you won't need to modify these values.
#
# You can also use `sheldon edit` to open up the config file in the default
# editor.
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme
# ---------------------------------------------------------------------------- #

# The `match` value specifies a global match sequence. If a plugin doesn't
# provide a `use` field then the first one of the following that matches at
# least one file will be used. The following is the default value.

match = [
    "{{ name }}.plugin.zsh",
    "{{ name }}.zsh",
    "{{ name }}.sh",
    "{{ name }}.zsh-theme",
    "*.plugin.zsh",
    "*.zsh",
    "*.sh",
    "*.zsh-theme"
]

# ---------------------------------------------------------------------------- #

# The `apply` value specifies global templates to apply by default. If a plugin
# doesn't provide an `apply` field then these will be used. The following is the
# default value.

apply = ["source"]

# ---------------------------------------------------------------------------- #

# The `[templates]` table defines templates available for use with plugins when
# they are rendered. The `each` field means that the template will be applied
# for each 'used' file in the plugin. You can override templates on an
# individual basis and add your own custom ones. The following is the default
# selection of provided templates (i.e. you don't have to put them in your
# config file).

[templates]
PATH = 'export PATH="{{ dir }}:$PATH"'
path = 'path=( "{{ dir }}" $path )'
fpath = 'fpath=( "{{ dir }}" $fpath )'
source = { value = 'source "{{ file }}"', each = true }

# ---------------------------------------------------------------------------- #

# The `[plugins]` table defines the plugins to load. You can modify this table
# directly or you can use one of the following `sheldon` commands which are
# provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon remove` to remove a plugin from the config file

# Example: add the Pure prompt under the name `pure`.
# ---------------------------------------------------

[plugins.pure]
# `github` sources provide the repository in the form {owner}/{repository}.
github = "sindresorhus/pure"
# `github`, git`, or `gist` sources may provide `branch`, `tag`, or `rev`.
tag = "v1.12.0"
# Apply the templates to these files in the plugin.
use = ["async.zsh", "pure.zsh"]
# Apply the `source` template to each of the above files.
apply = ["source"]

# Example: a plugin from a local directory.
# -----------------------------------------

[plugins.pyenv]
# `local` sources must provide the path to the source directory.
local = "~/.dotfiles/plugins"
# Most plugins can specify a directory within the source.
directory = 'pyenv'

# Example: an inline plugin.
# --------------------------

[plugins.www]
# `inline` plugins should provide the raw source to be rendered.
inline = 'www() { python3 -m http.server "$@" }'
