name: docs

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: docs/book/html

    - uses: extractions/setup-mdbook@v1

    - name: Build
      run: |
        mv docs/book/html/.git docs/book/.git
        mdbook build docs
        mv docs/book/.git docs/book/html/.git

    - name: Calculate Git short SHA
      id: git
      run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

    - name: Git commit
      run: |
        cd docs/book/html
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "publish docs for ${{ steps.git.outputs.short_sha }}"
        git push
        cd -
